### ISSUE TITLE
getTime delivers strange year value on RV 3032

### ISSUE THREAD

**Issue by kosh-mclien** [bitbank2/bb_rtc#1]
Hello,
I tested with output on the serial monitor. The relevant code snippets are:
setting the date:
myTime.tm_year = 2024;
myTime.tm_mon = 11;
myTime.tm_mday = 2;
rtc.setTime(&myTime);

getting the date:
rtc.getTime(&myTime);
Serial.printf("%02d.%02d.%04d", myTime.tm_mday, myTime.tm_mon, myTime.tm_year);

Which give the following output:
02.11.0124

after some digging and guessing, I found the RV 3032 stores the year only in the last 2 digits, which left me wondering, what the cause of the strange output was.

And we found this in the source:
void BBRTC::getTime(struct tm *pTime)
[...]
 } else if (_iRTCType == RTC_RV3032) {
[..]
        pTime->tm_mon = (((ucTemp[5] >> 4) & 1) * 10 + (ucTemp[5] & 0xf)) -1; // 0-11     
        pTime->tm_year = 100 + ((ucTemp[6] >> 4) * 10) + (ucTemp[6] & 0xf);

Since I did not understand what the idea behind the "100+" might be, I send this issue instead of a pull request.

The rest I tested works fine, thanks for the great work.

**Comment by bitbank2** [comment]
The year value is the number of years since 1900, not the full year amount. The RV3032 only holds 0-99 as the vear versus the DS3231 which holds 0-199. For reading the year, I assume the date in question is in the 21st century, so I add 100 by default.
